# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  push:
    branches: [ "testingartifactory" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "testingartifactory" ]
  schedule:
    - cron: '23 20 * * 0'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build --build-arg VCS_REF=$(git rev-parse HEAD) --build-arg VERSION_TAG=0.15.0 -t docker.io/gingalang-audr/sherlock-actions-github:${{ github.sha }} .

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/gingalang-audr/sherlock-actions-github:${{ github.sha }}'
          format: 'sarif'
          output: 'reports/sarif-sbom.json'

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER }}
          JF_ARTIFACTORY_USER: ${{ secrets.JF_ARTIFACTORY_USERNAME }}
          JF_ARTIFACTORY_PASSWORD: ${{ secrets.JF_ARTIFACTORY_TOKEN }}


      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'reports/sarif-sbom.json'


      - name: Upload to Artifactory
        run: |
          # Set the timestamp for the filename
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')

          # Set the repository path to the artifactory-build-info repository
          REPO_PATH="artifactory-build-info/sherlock/sarif-sbom-${TIMESTAMP}.json"

          # Upload the JSON file to Artifactory
          jf rt upload reports/sarif-sbom.json "${REPO_PATH}"

          echo "SBOM uploaded to Artifactory at ${REPO_PATH}"

      - name: Archive SBOM as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: sarif-sbom
          path: reports/sarif-sbom.json
          retention-days: 7
